slides:
  - file: postgres-1.md
    title: Postgres Basics
    slug: postgres-1
  - file: postgres-2.md
    title: Postgres Advanced (Constraints, Views, Indexes, Triggers)
    slug: postgres-2
  - file: postgres-3.md
    title: Postgres Transactions & Performance
    slug: postgres-3
